name: github pages

on:
  push:
    branches:
      - main

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - name: dd
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
