name: wasm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: wasm-pack build
        run: |
          wasm-pack build --target web
          mv "pkg/rwdv.js" "./wasm"
          mv "pkg/rwdv_bg.wasm" "./wasm"
          mv "pkg/rwdv_bg.wasm.d.ts" "./wasm"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets : '.github,LICENSE,Cargo.lock,*.toml,.gitignore,README.md,src,target'